from customer.CustomerCompanies import CustomerCompanies
from customer.CustomerDeathCertificates import CustomerDeathCertificates
from customer.CustomerEmergencyContacts import CustomerEmergencyContacts
from customer.CustomerMessages import CustomerMessages
from customer.CustomerReceivers import CustomerReceivers
from customer.CustomerTemplates import CustomerTemplates
from customer.CustomerUsers import CustomerUsers


CustomerCompanies
CustomerDeathCertificates
CustomerEmergencyContacts
CustomerMessages
CustomerReceivers
CustomerTemplates
CustomerUsers
